# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true


markdown: redcarpet
redcarpet:
  extensions: ["tables"]
exclude: ["*.Rmd"]
name: Manuel Mendes
