#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
name: Manuel Mendes

#
description: ""


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
#


# paginate: 10
# markdown: rdiscount
markdown: redcarpet  
#redcarpet:
#  extensions: ["tables"]
highlighter: pygments

#
baseurl: ""

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about'
  Archive: '/archive'



# The release of Jekyll Now that you're using
version: v1.1.0

