#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
name: Manuel Mendes

#
description: ""

title: On Test... (Jekyll)

# #######################################
url: http://mpmendespt.github.io/
shorturl:  mpmendespt.github.io


baseurl:  ''
paginate:  5

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#permalink: :title/
permalink: /:year/:month/:day/:title
#permalink: /blog/:year/:month/:day/:title
relative_permalinks: false

#
# paginate: 10
# markdown: rdiscount
markdown: redcarpet  
redcarpet:
  extensions: ["tables"]
highlighter: pygments



# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about'
  Archive: '/archive'


# The release of Jekyll Now that you're using
version: v1.1.0

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: /images/meSmall.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: mpmendespt
  instagram: 
  linkedin: 
  pinterest: 
  #rss: Y # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: mpmendespt
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: mpmendesptgithubio